2023-11-30 19:25:23,409 INFO    StreamThr :42535 [internal.py:wandb_internal():86] W&B internal server running at pid: 42535, started at: 2023-11-30 19:25:23.408772
2023-11-30 19:25:23,412 DEBUG   HandlerThread:42535 [handler.py:handle_request():146] handle_request: status
2023-11-30 19:25:23,413 INFO    WriterThread:42535 [datastore.py:open_for_write():85] open: /Users/owendugan/Documents/GitHub/Gym-Snake/wandb/run-20231130_192523-j8sjw3gc/run-j8sjw3gc.wandb
2023-11-30 19:25:23,415 DEBUG   SenderThread:42535 [sender.py:send():380] send: header
2023-11-30 19:25:23,454 DEBUG   SenderThread:42535 [sender.py:send():380] send: run
2023-11-30 19:25:26,960 INFO    SenderThread:42535 [retry.py:__call__():172] Retry attempt failed:
Traceback (most recent call last):
  File "/Users/owendugan/mambaforge/envs/snake/lib/python3.10/site-packages/urllib3/connection.py", line 203, in _new_conn
    sock = connection.create_connection(
  File "/Users/owendugan/mambaforge/envs/snake/lib/python3.10/site-packages/urllib3/util/connection.py", line 60, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "/Users/owendugan/mambaforge/envs/snake/lib/python3.10/socket.py", line 955, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno 8] nodename nor servname provided, or not known

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/owendugan/mambaforge/envs/snake/lib/python3.10/site-packages/urllib3/connectionpool.py", line 790, in urlopen
    response = self._make_request(
  File "/Users/owendugan/mambaforge/envs/snake/lib/python3.10/site-packages/urllib3/connectionpool.py", line 491, in _make_request
    raise new_e
  File "/Users/owendugan/mambaforge/envs/snake/lib/python3.10/site-packages/urllib3/connectionpool.py", line 467, in _make_request
    self._validate_conn(conn)
  File "/Users/owendugan/mambaforge/envs/snake/lib/python3.10/site-packages/urllib3/connectionpool.py", line 1096, in _validate_conn
    conn.connect()
  File "/Users/owendugan/mambaforge/envs/snake/lib/python3.10/site-packages/urllib3/connection.py", line 611, in connect
    self.sock = sock = self._new_conn()
  File "/Users/owendugan/mambaforge/envs/snake/lib/python3.10/site-packages/urllib3/connection.py", line 210, in _new_conn
    raise NameResolutionError(self.host, self, e) from e
urllib3.exceptions.NameResolutionError: <urllib3.connection.HTTPSConnection object at 0x11f42fbb0>: Failed to resolve 'api.wandb.ai' ([Errno 8] nodename nor servname provided, or not known)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/owendugan/mambaforge/envs/snake/lib/python3.10/site-packages/requests/adapters.py", line 486, in send
    resp = conn.urlopen(
  File "/Users/owendugan/mambaforge/envs/snake/lib/python3.10/site-packages/urllib3/connectionpool.py", line 844, in urlopen
    retries = retries.increment(
  File "/Users/owendugan/mambaforge/envs/snake/lib/python3.10/site-packages/urllib3/util/retry.py", line 515, in increment
    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='api.wandb.ai', port=443): Max retries exceeded with url: /graphql (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x11f42fbb0>: Failed to resolve 'api.wandb.ai' ([Errno 8] nodename nor servname provided, or not known)"))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/owendugan/mambaforge/envs/snake/lib/python3.10/site-packages/wandb/sdk/lib/retry.py", line 131, in __call__
    result = self._call_fn(*args, **kwargs)
  File "/Users/owendugan/mambaforge/envs/snake/lib/python3.10/site-packages/wandb/sdk/internal/internal_api.py", line 366, in execute
    return self.client.execute(*args, **kwargs)  # type: ignore
  File "/Users/owendugan/mambaforge/envs/snake/lib/python3.10/site-packages/wandb/vendor/gql-0.2.0/wandb_gql/client.py", line 52, in execute
    result = self._get_result(document, *args, **kwargs)
  File "/Users/owendugan/mambaforge/envs/snake/lib/python3.10/site-packages/wandb/vendor/gql-0.2.0/wandb_gql/client.py", line 60, in _get_result
    return self.transport.execute(document, *args, **kwargs)
  File "/Users/owendugan/mambaforge/envs/snake/lib/python3.10/site-packages/wandb/sdk/lib/gql_request.py", line 58, in execute
    request = self.session.post(self.url, **post_args)
  File "/Users/owendugan/mambaforge/envs/snake/lib/python3.10/site-packages/requests/sessions.py", line 637, in post
    return self.request("POST", url, data=data, json=json, **kwargs)
  File "/Users/owendugan/mambaforge/envs/snake/lib/python3.10/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "/Users/owendugan/mambaforge/envs/snake/lib/python3.10/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "/Users/owendugan/mambaforge/envs/snake/lib/python3.10/site-packages/requests/adapters.py", line 519, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='api.wandb.ai', port=443): Max retries exceeded with url: /graphql (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x11f42fbb0>: Failed to resolve 'api.wandb.ai' ([Errno 8] nodename nor servname provided, or not known)"))
2023-11-30 19:25:28,466 DEBUG   HandlerThread:42535 [handler.py:handle_request():146] handle_request: keepalive
2023-11-30 19:25:33,477 DEBUG   HandlerThread:42535 [handler.py:handle_request():146] handle_request: keepalive
2023-11-30 19:25:38,489 DEBUG   HandlerThread:42535 [handler.py:handle_request():146] handle_request: keepalive
2023-11-30 19:25:43,509 DEBUG   HandlerThread:42535 [handler.py:handle_request():146] handle_request: keepalive
2023-11-30 19:25:48,525 DEBUG   HandlerThread:42535 [handler.py:handle_request():146] handle_request: keepalive
2023-11-30 19:25:53,549 DEBUG   HandlerThread:42535 [handler.py:handle_request():146] handle_request: keepalive
2023-11-30 19:25:55,128 DEBUG   HandlerThread:42535 [handler.py:handle_request():146] handle_request: shutdown
2023-11-30 19:25:55,128 INFO    HandlerThread:42535 [handler.py:finish():866] shutting down handler
2023-11-30 19:25:55,575 INFO    WriterThread:42535 [datastore.py:close():294] close: /Users/owendugan/Documents/GitHub/Gym-Snake/wandb/run-20231130_192523-j8sjw3gc/run-j8sjw3gc.wandb
2023-11-30 19:26:01,159 INFO    SenderThread:42535 [dir_watcher.py:__init__():211] watching files in: /Users/owendugan/Documents/GitHub/Gym-Snake/wandb/run-20231130_192523-j8sjw3gc/files
2023-11-30 19:26:01,159 INFO    SenderThread:42535 [sender.py:_start_run_threads():1124] run started: j8sjw3gc with start time 1701390323.40941
2023-11-30 19:26:01,159 INFO    SenderThread:42535 [sender.py:finish():1536] shutting down sender
2023-11-30 19:26:01,159 INFO    SenderThread:42535 [dir_watcher.py:finish():358] shutting down directory watcher
2023-11-30 19:26:02,190 INFO    SenderThread:42535 [dir_watcher.py:finish():388] scan: /Users/owendugan/Documents/GitHub/Gym-Snake/wandb/run-20231130_192523-j8sjw3gc/files
2023-11-30 19:26:02,190 INFO    SenderThread:42535 [dir_watcher.py:finish():402] scan save: /Users/owendugan/Documents/GitHub/Gym-Snake/wandb/run-20231130_192523-j8sjw3gc/files/config.yaml config.yaml
2023-11-30 19:26:02,190 INFO    SenderThread:42535 [file_pusher.py:finish():175] shutting down file pusher
2023-11-30 19:26:02,190 INFO    SenderThread:42535 [file_pusher.py:join():181] waiting for file pusher
2023-11-30 19:26:03,612 INFO    wandb-upload_0:42535 [upload_job.py:push():131] Uploaded file /Users/owendugan/Documents/GitHub/Gym-Snake/wandb/run-20231130_192523-j8sjw3gc/files/config.yaml
2023-11-30 19:26:04,201 INFO    SenderThread:42535 [file_stream.py:finish():595] file stream finish called
2023-11-30 19:26:04,582 INFO    SenderThread:42535 [file_stream.py:finish():599] file stream finish is done
